website/models.py
from . import db
from sqlalchemy.sql import func

class ControlPointsData(db.Model):
    __tablename__ = 'control_points_data'

    sno = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    point_id = db.Column(db.String(10))
    arch1960_eastings = db.Column(db.Float)
    arch1960_northings = db.Column(db.Float)
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    heights = db.Column(db.Float)
    monument_status = db.Column(db.String(20))
    usage = db.Column(db.String(20))
    image_description = db.Column(db.String(255))
    satellite_image = db.Column(db.String(255))
    wgs84_eastings = db.Column(db.Float)
    wgs84_northings = db.Column(db.Float)


    def __init__(self, point_id, arch1960_eastings, arch1960_northings, latitude, longitude, heights, monument_status, usage, image_description, satellite_image, wgs84_eastings, wgs84_northings):
        self.point_id = point_id
        self.arch1960_eastings = arch1960_eastings
        self.arch1960_northings = arch1960_northings
        self.latitude = latitude
        self.longitude = longitude
        self.heights = heights
        self.monument_status = monument_status
        self.usage = usage
        self.image_description = image_description
        self.satellite_image = satellite_image
        self.wgs84_eastings = wgs84_eastings
        self.wgs84_northings = wgs84_northings

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'sihfshiajdoshioac'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:193720@localhost:5432/zahara'
    db.init_app(app)

    from website.views import views
    app.register_blueprint(views, url_prefix='/')
   

    return app

  

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from website.models import ControlPointsData
from . import db

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template('search.html')

@views.route('/general')
def general():
    data = ControlPointsData.query.all()
    serialized_data = []

    for item in data:
        serialized_item = {
            'point_id': item.point_id,
            'arch1960_eastings': item.arch1960_eastings,
            'arch1960_northings': item.arch1960_northings,
            'latitude': item.latitude,
            'longitude': item.longitude,
            'heights': item.heights,
            'monument_status': item.monument_status,
            'usage': item.usage,
            'image_description': item.image_description,
            'satellite_image': item.satellite_image,
            'wgs84_eastings': item.wgs84_eastings,
            'wgs84_northings': item.wgs84_northings
        }
        serialized_data.append(serialized_item)

    return render_template('general.html', data=serialized_data)



@views.route('/search', methods=['GET', 'POST'])
def search():
    if request.method == 'POST':
        point_id = request.form.get('search')
        point_id = point_id.upper()
        return redirect(url_for('views.control_point', point_id=point_id))
    else:
        search_term = request.args.get('search', '').strip()
        search_term = search_term.upper()
        if search_term:
            results = ControlPointsData.query.filter(ControlPointsData.point_id.like(f'%{search_term}%')).limit(10).all()
            suggestions = [result.point_id for result in results]
        else:
            suggestions = []
        return jsonify({'suggestions': suggestions})

@views.route('/control_point/<point_id>')
def control_point(point_id):
    control_point_data = ControlPointsData.query.filter_by(point_id=point_id).first()
    if control_point_data:
        return render_template('details.html', control_point_data=control_point_data)
        
    else:
        return redirect(url_for('views.home'))

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Search Page{% endblock %}</title>
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,300,300italic,400italic,600,700,600italic,700italic" rel="stylesheet">
  <!-- Bootstrap CSS CDN -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBO6cHgW53bx1dBHLsZa-Y8hAcVY9ZQW8E&callback=initMap" async defer></script>


  
  
</head>
<body style="background-image: url('{{ url_for('static', filename='images/background3.jpg') }}'); background-repeat: no-repeat; background-size: cover; background-position: center;">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbar"
        aria-controls="navbar"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="profile" href="/general">General</a>
        </div>
      </div>
    </nav>  

  <div class="container">
    {% block content %}{% endblock %}
    <br />
    <br />
  </div>

  <!-- Floating Container -->
  <div class="floating-container">
    <h3> Warning</h3>
    <p>Hide your IP address when using Control Point Finger — use a VPN</p>
    <button class="close-button" onclick="removeFloatingContainer()">X</button>
  </div>

    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">Scanfcode.com <i>CODE WANTS TO BE SIMPLE </i> is an initiative  to help the upcoming programmers with the code. Scanfcode focuses on providing the most efficient code or snippets as the code wants to be simple. We will help programmers build up concepts in different programming languages that include C, C++, Java, HTML, CSS, Bootstrap, JavaScript, PHP, Android, SQL and Algorithm.</p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Categories</h6>
            <ul class="footer-links">
              <li><a href="http://scanfcode.com/category/c-language/">C</a></li>
              <li><a href="http://scanfcode.com/category/front-end-development/">UI Design</a></li>
              <li><a href="http://scanfcode.com/category/back-end-development/">PHP</a></li>
              <li><a href="http://scanfcode.com/category/java-programming-language/">Java</a></li>
              <li><a href="http://scanfcode.com/category/android/">Android</a></li>
              <li><a href="http://scanfcode.com/category/templates/">Templates</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="http://scanfcode.com/about/">About Us</a></li>
              <li><a href="http://scanfcode.com/contact/">Contact Us</a></li>
              <li><a href="http://scanfcode.com/contribute-at-scanfcode/">Contribute</a></li>
              <li><a href="http://scanfcode.com/privacy-policy/">Privacy Policy</a></li>
              <li><a href="http://scanfcode.com/sitemap/">Sitemap</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2017 All Rights Reserved by 
         <a href="#">Scanfcode</a>.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>   
            </ul>
          </div>
        </div>
      </div>
  </footer>

  <!-- Bootstrap JavaScript and jQuery CDN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    function removeFloatingContainer() {
      var floatingContainer = document.querySelector('.floating-container');
      floatingContainer.parentNode.removeChild(floatingContainer);
    }
  </script>

  
</body>
</html>

website/templates/details.html
<!-- HTML code (details.html) -->
{% extends 'base.html' %}

{% block title %}Survey Station Description Card{% endblock %}

{% block content %}

  <h1>Survey Station Description Card</h1>

  <table>
    <!-- Table rows for point information -->
    <tr>
        <th>Project:</th>
        <td>Data Base for Survey Controls around UDSM</td>
    </tr>
    <tr>
        <th>Point ID:</th>
        <td>{{ control_point_data.point_id }}</td>
    </tr>
    <tr>
        <th>Description:</th>
        <td>{{ control_point_data.monument_status }}</td>
    </tr>
    <tr>
        <th>Location:</th>
        <td>{{ control_point_data.usage }}</td>
    </tr>
    <tr>
        <th>Instrument Used:</th>
        <td>LEICA VIVA</td>
    </tr>
    <tr>
        <th>District/Village:</th>
        <td>KINONDONI</td>
    </tr>
    <tr>
        <th>Approx. Chng:</th>
        <td>REGIONAL</td>
    </tr>
    <tr>
        <th>Method of Survey:</th>
        <td>GPS STATIC OBSERVATIONS</td>
    </tr>
    <tr>
        <!-- Table rows for coordinates -->
        <th>Coordinates:</th>
        <td>
            <table>
                <tr>
                    <th>UTM (ARC 1960) Northing:</th>
                    <td>{{ control_point_data.arch1960_northings }}</td>
                </tr>
                <tr>
                    <th>UTM (ARC 1960) Easting:</th>
                    <td>{{ control_point_data.arch1960_eastings }}</td>
                </tr>
                <tr>
                    <th>UTM (WGS 84) Northing:</th>
                    <td>{{ control_point_data.wgs84_northings }}</td>
                </tr>
                <tr>
                    <th>UTM (WGS 84) Easting:</th>
                    <td>{{ control_point_data.wgs84_eastings }}</td>
                </tr>
                <tr>
                    <th>Height (H):</th>
                    <td>{{ control_point_data.heights }}</td>
                </tr>
            </table>
            <br />
        </td>
    </tr>
    <tr>
      <!-- Table row for location sketch -->
      <th>Location Sketch:</th>
      <td class="center-image">
          {% if control_point_data.image_description %}
              <img src="{{ url_for('static', filename='images/control_point_images/' + control_point_data.image_description) }}" style="width: 500px; height: auto;">
          {% else %}
              No Data
          {% endif %}
      </td>
    </tr>
    <tr>
      <!-- Table row for satellite image -->
      <th>Description of the Point's Location:</th>
      <td class="center-image">
          {% if control_point_data.satellite_image %}
              <img src="{{ url_for('static', filename='images/sattelite_image/' + control_point_data.satellite_image) }}" style="width: 500px; height: auto;">
          {% else %}
              No Data
          {% endif %}
      </td>
    </tr>
    <!-- Table rows for additional information -->
    <tr>
        <th>Date of Survey:</th>
        <td>14th September 2020</td>
    </tr>
    <tr>
        <th>Surveyed By:</th>
        <td>Group One</td>
    </tr>
  </table>

  <br />
  <br />

  <div id="map-container">
    <h1>Current Location and Direction</h1>
    <p id="coordinates">Waiting for location...</p>
    <div id="map"></div>
    <br />
    <button id="directions-button">Get Directions</button>
  </div>

  <div id="route-details"></div>

  <script>

    
    function showPosition(position) {
      var latitude = position.coords.latitude;
      var longitude = position.coords.longitude;
      var coordinatesElement = document.getElementById("coordinates");
      coordinatesElement.textContent = "Latitude: " + latitude + ", Longitude: " + longitude;

      var mapElement = document.getElementById("map");
      var mapOptions = {
        center: { lat: latitude, lng: longitude },
        zoom: 12,
        styles: [
          // Map styles here
          {
            "featureType": "administrative",
            "elementType": "labels.text.fill",
            "stylers": [
              { "color": "#444444" }
            ]
          },
          {
            "featureType": "landscape",
            "elementType": "all",
            "stylers": [
              { "color": "#f2f2f2" }
            ]
          },
          {
            "featureType": "landscape.man_made",
            "elementType": "geometry.fill",
            "stylers": [
              { "gamma": "2.00" },
              { "color": "#c6c6c6" }
            ]
          },
          {
            "featureType": "poi",
            "elementType": "all",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "poi.park",
            "elementType": "geometry.fill",
            "stylers": [
              { "visibility": "on" },
              { "color": "#466149" },
              { "lightness": "-5" },
              { "gamma": "5.00" },
              { "weight": "0.01" }
            ]
          },
          {
            "featureType": "poi.park",
            "elementType": "labels.text",
            "stylers": [
              { "visibility": "on" },
              { "saturation": "-1" },
              { "color": "#000000" },
              { "gamma": "5.00" },
              { "weight": "0.01" }
            ]
          },
          {
            "featureType": "poi.school",
            "elementType": "geometry.fill",
            "stylers": [
              { "visibility": "on" },
              { "color": "#d38f8f" }
            ]
          },
          {
            "featureType": "poi.school",
            "elementType": "labels.icon",
            "stylers": [
              { "color": "#131212" }
            ]
          },
          {
            "featureType": "road",
            "elementType": "all",
            "stylers": [
              { "saturation": -100 },
              { "lightness": 45 }
            ]
          },
          {
            "featureType": "road.highway",
            "elementType": "all",
            "stylers": [
              { "visibility": "simplified" }
            ]
          },
          {
            "featureType": "road.arterial",
            "elementType": "geometry.fill",
            "stylers": [
              { "visibility": "on" },
              { "color": "#4a4161" },
              { "gamma": "2.00" },
              { "lightness": "4" }
            ]
          },
          {
            "featureType": "road.arterial",
            "elementType": "geometry.stroke",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "road.arterial",
            "elementType": "labels.text",
            "stylers": [
              { "color": "#010101" },
              { "gamma": "1.85" },
              { "lightness": "11" },
              { "saturation": "11" },
              { "weight": "0.01" }
            ]
          },
          {
            "featureType": "road.arterial",
            "elementType": "labels.icon",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "road.local",
            "elementType": "geometry.fill",
            "stylers": [
              { "visibility": "on" },
              { "color": "#b5a8be" }
            ]
          },
          {
            "featureType": "road.local",
            "elementType": "geometry.stroke",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "road.local",
            "elementType": "labels.text.fill",
            "stylers": [
              { "color": "#000000" },
              { "weight": "0.01" },
              { "gamma": "0.00" },
              { "lightness": "-100" }
            ]
          },
          {
            "featureType": "road.local",
            "elementType": "labels.text.stroke",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "transit",
            "elementType": "all",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "transit",
            "elementType": "geometry.fill",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "water",
            "elementType": "all",
            "stylers": [
              { "color": "#3d6576" },
              { "visibility": "on" }
            ]
          }
        ]
      };
      var map = new google.maps.Map(mapElement, mapOptions);

      var marker = new google.maps.Marker({
        position: { lat: {{ control_point_data.latitude }}, lng: {{ control_point_data.longitude }} }, // Replace with the actual coordinates from the database
        map: map
      });

      var directionsService = new google.maps.DirectionsService();
      var directionsRenderer = new google.maps.DirectionsRenderer({
        polylineOptions: {
          strokeColor: "#000000" // Set the direction line color to black
        },
        map: map,
        suppressMarkers: true
      });

      var directionsButton = document.getElementById("directions-button");
      directionsButton.addEventListener("click", function() {
        var destination = {
          lat: {{ control_point_data.latitude }},
          lng: {{ control_point_data.longitude }}
        };

        var request = {
          origin: { lat: latitude, lng: longitude },
          destination: destination,
          travelMode: 'DRIVING'
        };

        directionsService.route(request, function(result, status) {
          if (status == 'OK') {
            directionsRenderer.setDirections(result);

            // Extract and display route details
            var route = result.routes[0];
            var leg = route.legs[0];

            var distance = leg.distance.text;
            var duration = leg.duration.text;

            var routeDetailsElement = document.getElementById("route-details");
            routeDetailsElement.innerHTML = "Distance: " + distance + "<br>Duration: " + duration;

            directionsButton.style.display = "none";
          }
        });
      });
    }

    function showError(error) {
      var coordinatesElement = document.getElementById("coordinates");
      coordinatesElement.textContent = "Error getting location: " + error.message;
    }

    function getLocation() {
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition, showError);
      } else {
        var coordinatesElement = document.getElementById("coordinates");
        coordinatesElement.textContent = "Geolocation is not supported by this browser.";
      }
    }

    getLocation();
  </script>

{% endblock %}

website/templates/general.html
{% extends 'base.html' %}

{% block title %}Survey Station Description Card{% endblock %}

{% block content %}

  <h1>Welcome Home</h1>

  <div id="map-container">
    <h1>University of Dar es salaam control points</h1>
    <div id="map"></div>
  </div>

  <script>
    function showError(error) {
      var coordinatesElement = document.getElementById("coordinates");
      coordinatesElement.textContent = "Error getting location: " + error.message;
    }

    function getLocation() {
      var mapElement = document.getElementById("map");
      var mapOptions = {
        center: { lat: -6.7924, lng: 39.2083 }, // Set your desired default center
        zoom: 12,
        styles: [
        {
            "featureType": "administrative",
            "elementType": "labels.text.fill",
            "stylers": [
              { "color": "#444444" }
            ]
          },
          {
            "featureType": "landscape",
            "elementType": "all",
            "stylers": [
              { "color": "#f2f2f2" }
            ]
          },
          {
            "featureType": "landscape.man_made",
            "elementType": "geometry.fill",
            "stylers": [
              { "gamma": "2.00" },
              { "color": "#c6c6c6" }
            ]
          },
          {
            "featureType": "poi",
            "elementType": "all",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "poi.park",
            "elementType": "geometry.fill",
            "stylers": [
              { "visibility": "on" },
              { "color": "#466149" },
              { "lightness": "-5" },
              { "gamma": "5.00" },
              { "weight": "0.01" }
            ]
          },
          {
            "featureType": "poi.park",
            "elementType": "labels.text",
            "stylers": [
              { "visibility": "on" },
              { "saturation": "-1" },
              { "color": "#000000" },
              { "gamma": "5.00" },
              { "weight": "0.01" }
            ]
          },
          {
            "featureType": "poi.school",
            "elementType": "geometry.fill",
            "stylers": [
              { "visibility": "on" },
              { "color": "#d38f8f" }
            ]
          },
          {
            "featureType": "poi.school",
            "elementType": "labels.icon",
            "stylers": [
              { "color": "#131212" }
            ]
          },
          {
            "featureType": "road",
            "elementType": "all",
            "stylers": [
              { "saturation": -100 },
              { "lightness": 45 }
            ]
          },
          {
            "featureType": "road.highway",
            "elementType": "all",
            "stylers": [
              { "visibility": "simplified" }
            ]
          },
          {
            "featureType": "road.arterial",
            "elementType": "geometry.fill",
            "stylers": [
              { "visibility": "on" },
              { "color": "#4a4161" },
              { "gamma": "2.00" },
              { "lightness": "4" }
            ]
          },
          {
            "featureType": "road.arterial",
            "elementType": "geometry.stroke",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "road.arterial",
            "elementType": "labels.text",
            "stylers": [
              { "color": "#010101" },
              { "gamma": "1.85" },
              { "lightness": "11" },
              { "saturation": "11" },
              { "weight": "0.01" }
            ]
          },
          {
            "featureType": "road.arterial",
            "elementType": "labels.icon",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "road.local",
            "elementType": "geometry.fill",
            "stylers": [
              { "visibility": "on" },
              { "color": "#b5a8be" }
            ]
          },
          {
            "featureType": "road.local",
            "elementType": "geometry.stroke",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "road.local",
            "elementType": "labels.text.fill",
            "stylers": [
              { "color": "#000000" },
              { "weight": "0.01" },
              { "gamma": "0.00" },
              { "lightness": "-100" }
            ]
          },
          {
            "featureType": "road.local",
            "elementType": "labels.text.stroke",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "transit",
            "elementType": "all",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "transit",
            "elementType": "geometry.fill",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "water",
            "elementType": "all",
            "stylers": [
              { "color": "#3d6576" },
              { "visibility": "on" }
            ]
          }
        ]
      };
      var map = new google.maps.Map(mapElement, mapOptions);

      var rawData = `{{ data|tojson|safe }}`; // Retrieve the data from Flask and convert it to a JSON string
      var data;
      try {
        data = JSON.parse(rawData); // Convert the JSON string to a JavaScript object
      } catch (error) {
        console.error("Error parsing JSON data:", error);
        return;
      }

      // Add markers based on the retrieved data
      var markers = [];
      for (var i = 0; i < data.length; i++) {
        var marker = new google.maps.Marker({
          position: { lat: data[i].latitude, lng: data[i].longitude },
          map: map,
          label: {
            text: data[i].point_id, // Customize the label as needed
            color: 'black',
            fontWeight: 'bold',
            fontSize: '12px',
            labelOrigin: new google.maps.Point(0, 50) // Adjust the vertical position of the label
          }
        });

        markers.push(marker);

        // Add click event listener to each marker
        marker.addListener("click", function () {
          // Zoom in and center the map on the clicked marker
          map.setZoom(15);
          map.setCenter(this.getPosition());

          // Highlight the clicked marker
          this.setAnimation(google.maps.Animation.BOUNCE);
          setTimeout(function () {
            this.setAnimation(null);
          }.bind(this), 2000);
        });
      }
    }

    // Call the getLocation function once the DOM has fully loaded
    document.addEventListener("DOMContentLoaded", function() {
      getLocation();
    });
  </script>

{% endblock %}

website/templates/search.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block styles %}
<style>
    .floating-ad.left-ad {
        background-color: #f8f8f8; /* Set the desired background color */
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="floating-ad left-ad">
        <!-- Left Ad Content -->
        <h3>Left Ad</h3>
        <p>Ad description goes here</p>
      </div>
    </div>
    <div class="col-md-6">
      <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo" class="logo">
      <form action="{{ url_for('views.search') }}" method="post"> <!-- Updated endpoint name to 'views.search' -->
        <input type="text" name="search" id="search-input" placeholder="Enter your search term">
        <br>
        <input type="submit" value="Search">
      </form>
    </div>
    <div class="col-md-3">
      <div class="floating-ad right-ad">
        <!-- Right Ad Content -->
        <h3>Point ID</h3>
        <p>Suggestion Box</p>
        <div id="suggestions" class="mt-3"></div> <!-- Added a container for search suggestions -->
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    var searchInput = $('#search-input');
    var suggestionBox = $('#suggestions');

    searchInput.on('input', function() {
      var searchTerm = searchInput.val();
      $.get('/search', { search: searchTerm }, function(data) { // Updated the AJAX request URL to '/search'
        var suggestions = data.suggestions;
        suggestionBox.empty();

        if (suggestions.length > 0) {
          var suggestionList = $('<ul>').addClass('list-group'); // Create an unordered list with Bootstrap class

          for (var i = 0; i < suggestions.length; i++) {
            var suggestion = suggestions[i];
            var suggestionItem = $('<li>').addClass('list-group-item').text(suggestion); // Create a list item with Bootstrap class
            suggestionItem.on('click', function() {
              searchInput.val($(this).text());
              suggestionBox.empty();
            });

            suggestionList.append(suggestionItem); // Append the list item to the unordered list
          }

          suggestionBox.append(suggestionList); // Append the unordered list to the suggestion box
        } else {
          suggestionBox.text('No suggestions found.');
        }
      });
    });
  });
</script>
{% endblock %}